# ==== Science Image ====
FROM oaklight/texlive:base

# Install additional packages for the science version
RUN apt-get update && apt-get install -y \
        texlive-science \
        texlive-latex-extra \
        texlive-extra-utils \
        texlive-fonts-extra \
        texlive-fonts-recommended \
    && rm -rf /var/lib/apt/lists/*